version: '3'


services:
  web: &web
    build:
      context: .
    image: ghcr.io/reflejar/pis-dash:latest
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    # command: python main.py censos